### ISSUE TITLE
cmake: Unknown arguments specified

### ISSUE THREAD

**Issue by Andarwinux** [Wohlhabend-Networks/LuaJIT#24]
```
CMake Error at src/CMakeLists.txt:155 (if):
  if given arguments:

    "ANDROID" "AND" "(" "LESS" "21" ")"

  Unknown arguments specified
```
when archlinux crosscompile mingw64 luajit
cmake version 3.27.9

**Comment by Wohlstand** [comment]
I may guess that because of the `CMAKE_SYSTEM_VERSION` was being undefined 🤔

**Comment by Andarwinux** [comment]
Yes, CMAKE_SYSTEM_VERSION does not exist by default when cross-compile. I solved this problem by manually define CMAKE_SYSTEM_VERSION to an arbitrary value.
